airflow:
  connections:
    - conn_id: carone_api
      conn_type: http
      conn_host: carone.com.ar
      conn_schema: https
    - conn_id: deruedas_web
      conn_type: http
      conn_host: www.deruedas.com.ar
      conn_schema: https

  variables:
    - variable_name: "grupo"
      variable_value: "5K09-03"
    - variable_name: "meta_volumen"
      variable_value: "1001"
    - variable_name: "deruedas_delay_seconds"
      variable_value: "2.0"
    - variable_name: "deruedas_max_pages"
      variable_value: "200"
    - variable_name: "carone_max_pages"
      variable_value: "100"
